# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-27376-wolf-virtual-machine/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter areaStrategy 2
    set rt::partid xc7a100tfgg484-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/wolf/rocc-accelerator/verilog/utils/nasti_lite_bridge
    /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/clk_wiz_0
    /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/axi_crossbar_0/hdl
    /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/axi_clock_converter_0/hdl
  } {
      /home/wolf/rocc-accelerator/verilog/utils/nasti_lite_bridge/nasti_lite_writer.sv
      /home/wolf/rocc-accelerator/verilog/utils/nasti_lite_bridge/nasti_lite_bridge.sv
      /home/wolf/rocc-accelerator/verilog/utils/nasti_lite_bridge/nasti_lite_reader.sv
      /tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/wolf/rocc-accelerator/verilog/utils/nasti_lite_bridge
    /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/clk_wiz_0
    /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/axi_crossbar_0/hdl
    /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/axi_clock_converter_0/hdl
  } {
      ./.Xil/Vivado-27376-wolf-virtual-machine/realtime/clk_wiz_0_stub.v
      ./.Xil/Vivado-27376-wolf-virtual-machine/realtime/axi_crossbar_0_stub.v
      ./.Xil/Vivado-27376-wolf-virtual-machine/realtime/axi_uart16550_0_stub.v
      ./.Xil/Vivado-27376-wolf-virtual-machine/realtime/axi_clock_converter_0_stub.v
      ./.Xil/Vivado-27376-wolf-virtual-machine/realtime/mig_7series_0_stub.v
      ./.Xil/Vivado-27376-wolf-virtual-machine/realtime/Mul8bit_stub.v
      /home/wolf/rocc-accelerator/verilog/utils/sram_modified.v
      /home/wolf/rocc-accelerator/verilog/AXIMem.v
      /home/wolf/rocc-accelerator/verilog/testbench/dut_top_tb.v
      /home/wolf/rocc-accelerator/verilog/uart.v
      /home/wolf/rocc-accelerator/verilog/peri/DTModule.v
      /home/wolf/rocc-accelerator/verilog/grh_chip_top.v
      /home/wolf/rocc-accelerator/verilog/peri/uart.v
      /home/wolf/rocc-accelerator/verilog/peri/spi.v
      /home/wolf/rocc-accelerator/verilog/utils/AsyncResetReg.v
      /home/wolf/rocc-accelerator/verilog/utils/narrower.v
      /home/wolf/rocc-accelerator/verilog/peri/bram_storage.v
      /home/wolf/rocc-accelerator/verilog/utils/EICG_wrapper.v
      /home/wolf/rocc-accelerator/verilog/freechips.rocketchip.system.GRHRV32FPGAConfig.v
      /home/wolf/rocc-accelerator/verilog/AXIMmio.v
      /home/wolf/rocc-accelerator/verilog/utils/plusarg_reader.v
      /home/wolf/rocc-accelerator/verilog/peri/bram.v
    }
      rt::read_vhdl -lib xpm /tools/Xilinx/Vivado/2019.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-27376-wolf-virtual-machine/realtime/chip_top_synth.xdc
    rt::sdcChecksum
    set rt::top chip_top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
    rt::set_parameter syncControlMinFanout 0
    rt::set_parameter minInstsInControlSet 1
# MODE: 
    rt::set_parameter webTalkPath {/home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.cache/wt}
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-27376-wolf-virtual-machine/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
