# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/Mul8bit/Mul8bit.xci
# IP: The module: 'Mul8bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/Mul8bit/Mul8bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mul8bit'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/Mul8bit/Mul8bit.xci
# IP: The module: 'Mul8bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/Mul8bit/Mul8bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mul8bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
