# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache ./.Xil/Vivado-20605-ubuntu/incrSyn
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.cache/wt [current_project]
set_property parent.project_path /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog /home/wolf/rocket-chip/rocc-accelerator/verilog64/utils/nasti_lite_bridge/nasti_request.vh
read_verilog -library xil_defaultlib -sv {
  /home/wolf/rocket-chip/rocc-accelerator/verilog64/utils/nasti_lite_bridge/nasti_lite_bridge.sv
  /home/wolf/rocket-chip/rocc-accelerator/verilog64/utils/nasti_lite_bridge/nasti_lite_reader.sv
  /home/wolf/rocket-chip/rocc-accelerator/verilog64/utils/nasti_lite_bridge/nasti_lite_writer.sv
}
read_verilog -library xil_defaultlib {
  /home/wolf/rocket-chip/rocc-accelerator/verilog64/AXIMem.v
  /home/wolf/rocket-chip/rocc-accelerator/verilog64/AXIMmio.v
  /home/wolf/rocket-chip/rocc-accelerator/verilog64/peri/DTModule.v
  /home/wolf/rocket-chip/rocc-accelerator/verilog64/GRHRV64FPGAConfig.v
  /home/wolf/rocket-chip/rocc-accelerator/verilog64/utils/narrower.v
  /home/wolf/rocket-chip/rocc-accelerator/verilog64/utils/plusarg_reader.v
  /home/wolf/rocket-chip/rocc-accelerator/verilog64/utils/sram_modified.v
  /home/wolf/rocket-chip/rocc-accelerator/verilog64/peri/uart.v
  /home/wolf/rocket-chip/rocc-accelerator/verilog64/grh_chip_top.v
}
read_ip -quiet /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.srcs/sources_1/ip/axi_uart16550_0/axi_uart16550_0.xci
set_property used_in_implementation false [get_files -all /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.srcs/sources_1/ip/axi_uart16550_0/axi_uart16550_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.srcs/sources_1/ip/axi_uart16550_0/axi_uart16550_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.srcs/sources_1/ip/axi_uart16550_0/axi_uart16550_0.xdc]

read_ip -quiet /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.srcs/sources_1/ip/axi_clock_converter_0/axi_clock_converter_0.xci
set_property used_in_synthesis false [get_files -all /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.srcs/sources_1/ip/axi_clock_converter_0/axi_clock_converter_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.srcs/sources_1/ip/axi_clock_converter_0/axi_clock_converter_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.srcs/sources_1/ip/axi_clock_converter_0/axi_clock_converter_0_ooc.xdc]

read_ip -quiet /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]

read_ip -quiet /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.srcs/sources_1/ip/Mul8bit/Mul8bit.xci
set_property used_in_implementation false [get_files -all /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc_64/minisys_with_grh_rocc_64.srcs/sources_1/ip/Mul8bit/Mul8bit_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/wolf/rocket-chip/rocc-accelerator/constraints/Minisys_Board_Pin_Map.xdc
set_property used_in_implementation false [get_files /home/wolf/rocket-chip/rocc-accelerator/constraints/Minisys_Board_Pin_Map.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top grh_chip_top -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef grh_chip_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file grh_chip_top_utilization_synth.rpt -pb grh_chip_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
