# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/axi_crossbar_0/axi_crossbar_0.xci
# IP: The module: 'axi_crossbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/axi_crossbar_0/axi_crossbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_crossbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/axi_crossbar_0/axi_crossbar_0.xci
# IP: The module: 'axi_crossbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/wolf/rocket-chip/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/axi_crossbar_0/axi_crossbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_crossbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
