# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.cache/wt [current_project]
set_property parent.project_path /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog /home/wolf/rocc-accelerator/verilog/utils/nasti_lite_bridge/nasti_request.vh
read_verilog -library xil_defaultlib -sv {
  /home/wolf/rocc-accelerator/verilog/utils/nasti_lite_bridge/nasti_lite_writer.sv
  /home/wolf/rocc-accelerator/verilog/utils/nasti_lite_bridge/nasti_lite_bridge.sv
  /home/wolf/rocc-accelerator/verilog/utils/nasti_lite_bridge/nasti_lite_reader.sv
}
read_verilog -library xil_defaultlib {
  /home/wolf/rocc-accelerator/verilog/utils/sram_modified.v
  /home/wolf/rocc-accelerator/verilog/AXIMem.v
  /home/wolf/rocc-accelerator/verilog/testbench/dut_top_tb.v
  /home/wolf/rocc-accelerator/verilog/uart.v
  /home/wolf/rocc-accelerator/verilog/peri/DTModule.v
  /home/wolf/rocc-accelerator/verilog/grh_chip_top.v
  /home/wolf/rocc-accelerator/verilog/peri/uart.v
  /home/wolf/rocc-accelerator/verilog/peri/spi.v
  /home/wolf/rocc-accelerator/verilog/utils/AsyncResetReg.v
  /home/wolf/rocc-accelerator/verilog/utils/narrower.v
  /home/wolf/rocc-accelerator/verilog/peri/bram_storage.v
  /home/wolf/rocc-accelerator/verilog/utils/EICG_wrapper.v
  /home/wolf/rocc-accelerator/verilog/freechips.rocketchip.system.GRHRV32FPGAConfig.v
  /home/wolf/rocc-accelerator/verilog/AXIMmio.v
  /home/wolf/rocc-accelerator/verilog/utils/plusarg_reader.v
  /home/wolf/rocc-accelerator/verilog/peri/bram.v
}
read_ip -quiet /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/axi_crossbar_0/axi_crossbar_0.xci
set_property used_in_implementation false [get_files -all /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/axi_crossbar_0/axi_crossbar_0_ooc.xdc]

read_ip -quiet /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/axi_uart16550_0/axi_uart16550_0.xci
set_property used_in_implementation false [get_files -all /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/axi_uart16550_0/axi_uart16550_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/axi_uart16550_0/axi_uart16550_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/axi_uart16550_0/axi_uart16550_0.xdc]

read_ip -quiet /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/axi_clock_converter_0/axi_clock_converter_0.xci
set_property used_in_synthesis false [get_files -all /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/axi_clock_converter_0/axi_clock_converter_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/axi_clock_converter_0/axi_clock_converter_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/axi_clock_converter_0/axi_clock_converter_0_ooc.xdc]

read_ip -quiet /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/mig_7series_0/mig_7series_0.xci
set_property used_in_implementation false [get_files -all /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/mig_7series_0/mig_7series_0/user_design/constraints/mig_7series_0.xdc]

read_ip -quiet /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/Mul8bit/Mul8bit.xci
set_property used_in_implementation false [get_files -all /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/sources_1/ip/Mul8bit/Mul8bit_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/constrs_1/imports/constraints/Minisys_Board_Pin_Map.xdc
set_property used_in_implementation false [get_files /home/wolf/rocc-accelerator/vivado_project/minisys_with_grh_rocc/minisys_with_grh_rocc.srcs/constrs_1/imports/constraints/Minisys_Board_Pin_Map.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top chip_top -part xc7a100tfgg484-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef chip_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file chip_top_utilization_synth.rpt -pb chip_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
